# Generated by Django 5.1 on 2024-09-10 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_offprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offprice',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
